### ISSUE TITLE
Missing bower main file

### ISSUE THREAD

**Issue by eranimo** [DaveWM/ngPopoverButton#2]
Please add the main javascript file of the project to the main attribute of the bower file so that auto-injecting tools like gulp-inject can work.

Also, why does this need to be a button?

**Comment by DaveWM** [comment]
@eranimo I've updated bower.json, should now have the correct main files. 

The reason this is a button is just because it would be quite difficult to generalise the directive to use any element type. If you want to have a go at this, then feel free to create a new issue for it, then submit a PR :)

You could also use the [angular-strap popover directive](http://mgcrea.github.io/angular-strap/#/popovers#popovers) which allows you to have dynamic popover content.
